### ISSUE TITLE
release 1.7.0 not scaling

### ISSUE THREAD

**Issue by salavessa** [kubernetes-incubator/cluster-proportional-autoscaler#61]
Hi,

Latest version `1.7.0` doesn't seem to be working at all (tested in k8s `v1.11.9`, `v1.13.10` and `v1.15.2` with `RBAC` and wasn't able to make it autoscale anything - it only shows the initial log message `autoscaler.go:49] Scaling Namespace: default, Target: deployment/nginx-autoscale-example` and that's it).
Exactly same deployment (e.g. examples/linear.yaml) works fine when using cluster-proportional-autoscaler releases `1.5.0` or `1.6.0`. Just need to exec `kubectl set image deployment/nginx-autoscaler autoscaler=gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.6.0` and is all good.

As a side note: deployments in example yml files are also broken as `selector` is mandatory for api version `apps/v1`: `error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec`

Thanks!

**Comment by MrHohn** [comment]
Thanks for reporting this. https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/pull/62 is fixing the example files. Also I'm looking into the not scaling issue, will report back soon.

**Comment by MrHohn** [comment]
Turned out we re-vendored client-go (https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/pull/59) and broke the controller.

The culprit is that `reflector.Run()` no longer spawns a new goroutine and becomes blocking:

https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/513df764a729167ab44fc1f1544481a8820e1cf5/vendor/k8s.io/client-go/tools/cache/reflector.go#L184-L193

https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/fb1db9b7a39a265b1afea185f107057e07f3402d/vendor/k8s.io/client-go/tools/cache/reflector.go#L119-L128

Will send a fix soon.

**Comment by salavessa** [comment]
> 
> 
> Thanks for reporting this. #62 is fixing the example files. Also I'm looking into the not scaling issue, will report back soon.

Thanks for the fast action 👍
I guess one file was missed: `examples/linear-defaultparams.yaml`
And maybe the comments in the end should be kept as before because having `serviceAccountName: cluster-proportional-autoscaler-example` makes it directly dependable on the components of `examples/RBAC/RBAC-configs.yaml` file for the autoscaler pod to start... or else the contents of the `RBAC-configs.yaml` file could be prepended to each one of the example files, but it may be just a lot of duplication.

**Comment by MrHohn** [comment]
@salavessa Thanks for looking into that. Makes sense, will update that soon.

**Comment by MrHohn** [comment]
I will soon cut a new release (1.7.1).

**Comment by salavessa** [comment]
1.7.1 is working fine for same scenarios that were previously failing for me.
Closing...
Thanks
